### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by Xenokkah** [Ilysen/SLIssueTracker#5]
### Description
This is a test bug.

### Discovery
* **Testers:** Sin
* **Time (include time zone - estimates are fine):** 11:39:44 PM EST

### Game Version
9.0.0

### To Reproduce
 - Log into github
 - Do the thing

### Expected Behavior
A test bug will be created.

### Media
N/A

**Comment by Ilysen** [comment]
Fix it yourself IDIOT
